apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronoos
  namespace: default
  labels:
    app: kronoos
spec:
  selector:
    matchLabels:
      app: kronoos
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kronoos
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: kronoos
          image: rodrigovenancioverissimo/kronoos:latest
          resources:
            requests:
              cpu: 500m
              memory: 2000Mi
            limits:
              cpu: 500m
              memory: 2000Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 3000
              name: kronoos
      restartPolicy: Always
