apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rodrigovenancioverissimo/kronoos_api:1
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
