-- CreateTable
CREATE TABLE "Records" (
    "id" SERIAL NOT NULL,
    "nrInst" INTEGER NOT NULL,
    "nrAgencia" INTEGER NOT NULL,
    "cdClient" INTEGER NOT NULL,
    "nmClient" TEXT NOT NULL,
    "nrCpfCnpj" TEXT,
    "nrContrato" INTEGER NOT NULL,
    "dtContrato" TIMESTAMP(3) NOT NULL,
    "qtPrestacoes" INTEGER NOT NULL,
    "vlTotal" TEXT NOT NULL,
    "cdProduto" INTEGER NOT NULL,
    "dsProduto" TEXT NOT NULL,
    "cdCarteira" INTEGER NOT NULL,
    "dsCarteira" TEXT NOT NULL,
    "nrProposta" INTEGER NOT NULL,
    "nrPresta" INTEGER NOT NULL,
    "tpPresta" TEXT NOT NULL,
    "nrSeqPre" INTEGER NOT NULL,
    "dtVctPre" TIMESTAMP(3) NOT NULL,
    "vlMora" TEXT NOT NULL,
    "vlMulta" TEXT NOT NULL,
    "vlOutAcr" TEXT NOT NULL,
    "vlIof" TEXT NOT NULL,
    "vlAtual" TEXT NOT NULL,
    "vlDescon" TEXT NOT NULL,
    "vlPresta" TEXT NOT NULL,
    "idSituac" TEXT NOT NULL,
    "idSitVen" TEXT NOT NULL,
    "isDocumentValid" BOOLEAN NOT NULL,
    "isPaymentValid" BOOLEAN NOT NULL,

    CONSTRAINT "Records_pkey" PRIMARY KEY ("id")
);
